### ISSUE TITLE
Populate the jumplist

### ISSUE THREAD

**Issue by BlackCapCoder** [anschnapp/move-less#3]
After using move-less, the expected behavior of `''` is to take me to where I were before the jump. This can be achieved with `nmap <leader>m m':call MoveLessMove()<cr>`, but it would be nice if it was the default behavior.

**Comment by anschnapp** [comment]
Hi @BlackCapCoder, thank you for your feedback! 😄 

My intension was that the user will user a navigation method for leaving the move less mode which already is recorded to the jump list (like search with `/` using easymotion, jump with `g[linenumber]`...

This is meant with this section inside the documentation:

> If you found your function you could jump or walk to it by simple use your prefered way to do it. (i like easymotion a lot for this step but it's not necessary). If you use a action which writes to the jumplist you could easily switch between source and target positoon afterwards.

So, for case of using a jump command for ending move less mode you don't need a custom keybinding for navigating back (and forward again).
How do you navigate away from the folded line to the code line you wanted? Are you "walking" (using j or k)?

Maybe I could try to determine if the user has used a navigation which manipulates the jumplist and otherwise I add the entry myself to it (i want to avoid adding 2 entries in the jumplist for one move less navigation). 
But I don't know if it's feasible and if it's a common case that the user don't make jump command at the end of the move less mode which supports already jump list recording.

What do you think about it?

**Comment by BlackCapCoder** [comment]
`/` and `[linenumber]G` does indeed work. I am using relative numbers, so it is more convenient for me to leave MoveLessMode with `[count]j` or `k`, which are not recorded in the jumplist. Relative line numbers are fairly popular, so I think this could be a pretty common case.

Also, the jumplist cannot contain sequential duplicates, so adding an entry shouldn't be an issue?

https://asciinema.org/a/LwXmC3QpyzBiAiC4eOmQJ1JE0

**Comment by anschnapp** [comment]
yes relative numbers are a cool way to combine with move-less mode.

> Also, the jumplist cannot contain sequential duplicates, so adding an entry shouldn't be an issue?
Good to know! 😄 

This is a good feature request, I will implement it in my next version. (will be coming soon)

**Comment by anschnapp** [comment]
@BlackCapCoder I have added the feature.  (see commit above)

Would be glad if you could test if this works for you 😄

**Comment by BlackCapCoder** [comment]
@anschnapp The newest version works as expected for me. Thank you for the quick response!
